version: "3.7"

x-base-config: &base-config
  volumes:
    - ./:/var/tripod-php
    - ./vendor:/var/tripod-php/vendor:delegated
  links:
    - "mongo32:mongodb"
    - redis
  depends_on:
    - mongo32
    - redis
  working_dir: /var/tripod-php
  env_file: .env

services:
  php55:
    # build:
    #   context: ./docker
    #   dockerfile: Dockerfile-php55
    image: talis/tripod-php:php55-latest
    <<: *base-config

  php73:
    # build:
    #   context: ./docker
    #   dockerfile: Dockerfile-php73
    image: talis/tripod-php:php73-latest
    <<: *base-config

  mongo32:
    image: mongo:3.2.21

  redis:
    image: redis:6.2.6
