x-base-config: &base-config
  volumes:
    - ./:/var/tripod-php
  depends_on:
    - mongodb
    - redis
  working_dir: /var/tripod-php
  env_file: .env

services:
  php74:
    build:
      context: ./docker
      dockerfile: php74.Dockerfile
    image: talis/tripod-php:php74-latest
    <<: *base-config

  php84:
    build:
      context: ./docker
      dockerfile: php84.Dockerfile
    image: talis/tripod-php:php84-latest
    <<: *base-config

  php85:
    build:
      context: ./docker
      dockerfile: php85.Dockerfile
    image: talis/tripod-php:php85-latest
    <<: *base-config

  mongodb:
    image: mongo:4.0

  redis:
    image: valkey/valkey:8-alpine
