x-base-config: &base-config
  volumes:
    - ./:/var/tripod-php
  depends_on:
    - mongodb
    - redis
  working_dir: /var/tripod-php
  env_file: .env

services:
  php73:
    build:
      context: ./docker
      dockerfile: Dockerfile-php73
    image: talis/tripod-php:php73-latest
    <<: *base-config

  php74:
    build:
      context: ./docker
      dockerfile: Dockerfile-php74
    image: talis/tripod-php:php74-latest
    <<: *base-config

  mongodb:
    image: mongo:3.6.23

  redis:
    image: redis:6.2.6
