version: 2.1

jobs:
  test:
    parameters:
      php_version:
        type: string
    docker:
      - image: talis/tripod-php:<< parameters.php_version >>-latest
        environment:
          RESQUE_SERVER: redis
      - image: mongo:3.2.21
        name: mongodb
      - image: redis:6.2.6
        name: redis
    steps:
      - checkout
      - run: composer install
      - run: ./vendor/bin/phpunit test/unit
      - run: ./vendor/bin/phpunit test/performance

workflows:
  build_and_test:
    jobs:
      - test:
          matrix:
            parameters:
              php_version:
                - php55
                - php73
