version: 2.1
executors:
  linux:       
    docker:
      - image: cimg/base:2020.01
      - image: rossfsinger/mongo-2.6.12
      - image: redis:latest
commands:
  install_php_mongo:
    description: installs mongo pecl library
    steps:
      - run: php -i
      - run: sudo apt-get update
      - run: sudo apt-get install -y php-mongodb
      # - run: sudo pecl channel-update pecl.php.net
      # - run: sudo pecl install mongodb-1.1.9      
  unit_tests:
    steps:
      - run: ./vendor/bin/phpunit test/unit  
orbs:
  php: circleci/php@1.1.0

jobs:
  test:
    parameters:
      php-version:
        type: string
    executor: linux
    steps:
      - checkout
      - php/install-php:
          version: << parameters.php-version >>
      - install_php_mongo
      - php/install-composer
      - php/install-packages
      - unit_tests

workflows:
  build_and_test:
    jobs:
      - test: 
          php-version: "5.6"
        
