version: 2.1

parameters:
  version:
    type: string
    
commands:
  build:
    steps:
      - run: docker-compose build --no-cache << pipeline.parameters.version >> 
  install_composer_dependencies:
    name: Install composer dependencies for << pipeline.parameters.version >>
    steps:
      - run: docker-compose run << pipeline.parameters.version >> composer install
  unit_tests:
    name: Run unit tests for << pipeline.parameters.version >>
    steps:
      - run: docker-compose run << pipeline.parameters.version >> ./vendor/bin/phpunit test/unit  
  performance_tests:
    name: Run performance tests for << pipeline.parameters.version >>
    steps:
     - run: docker-compose run << pipeline.parameters.version >> ./vendor/bin/phpunit test/performance

jobs:
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout      
      - install_composer_dependencies:
        version: << pipeline.parameters.version >>
      - unit_tests
        version: << pipeline.parameters.version >>
      - performance_tests
        version: << pipeline.parameters.version >>

workflows:
  build_and_test:
    jobs:
      - test:
          matrix:
            parameters:
              version: ["php55", "php56", "php70"]