version: 2.1

commands:
  build:
    steps:
      - run: docker-compose build --no-cache php55  
  install_composer_dependencies:
    steps:
      - run: docker-compose run php55 composer install
  unit_tests:
    steps:
      - run: docker-compose run php55 ./vendor/bin/phpunit test/unit  
  performance_tests:
    steps:
     - run: docker-compose run php55 ./vendor/bin/phpunit test/performance

jobs:
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout      
      - build
      - install_composer_dependencies
      - unit_tests
      - performance_tests

workflows:
  build_and_test:
    jobs:
      - test