version: 2.1
executors:
  linux:
    docker:
      - image: cimg/base:2020.01
      
commands:
  unit_tests:
    steps:
      - run: ./vendor/bin/phpunit test/unit  
  performance_tests:
    steps:
     - run: ./vendor/bin/phpunit
orbs:
  php: circleci/php@1.1.0

jobs:
  test:
    parameters:
      php-version:
        type: string
    executor: linux
    steps:
      - checkout
      - unit_tests
      - integration_tests

workflows:
  build_and_test:
    jobs:
      - test: 
          php-version: "5.5"
        
