version: 2.1


commands:
  build:
    steps:
      - run: docker-compose build --no-cache << pipeline.parameters.version >> 
  install_composer_dependencies:
    steps:
      - run: docker-compose run << pipeline.parameters.version >> composer install
  unit_tests:
    steps:
      - run: docker-compose run << pipeline.parameters.version >> ./vendor/bin/phpunit test/unit  
  performance_tests:
    steps:
     - run: docker-compose run << pipeline.parameters.version >> ./vendor/bin/phpunit test/performance

jobs:
  test:
    parameters:
      version:
        type: string
        default: "php55"
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout      
      - run: docker-compose build --no-cache << parameters.version >> 
      - run: docker-compose run << parameters.version >> composer install
      - run: docker-compose run << parameters.version >> ./vendor/bin/phpunit test/unit
      - run: docker-compose run << parameters.version >> ./vendor/bin/phpunit test/performance
      # - unit_tests
      # - performance_tests

workflows:
  build_and_test:
    jobs:
      - test:
        matrix:
          parameters:
            version: ["php55", "php56", "php70"]