version: 2.1
executors:
  linux:       
    docker:
      - image: cimg/base:2020.01
      
commands:
  unit_tests:
    steps:
      - run: docker-compose run php55 ./vendor/bin/phpunit test/unit  
  performance_tests:
    steps:
     - run: docker-compose run php55 ./vendor/bin/phpunit

jobs:
  test:
    parameters:
      php-version:
        type: string
    executor: linux
    steps:
      - checkout
      - unit_tests
      - performance_tests

workflows:
  build_and_test:
    jobs:
      - test